### ISSUE TITLE
[Help request] How to setup tunneling with nginx

### ISSUE THREAD

**Issue by DerKnerd** [TheSpaghettiDetective/obico-server#721]
Hey everyone,

I just installed the self hosted version of obico and want to connect it using OctoApp. For that to work I need to setup tunneling, but sadly I just can't get it to work. Here is the nginx and obico configuration:

docker-compose.override.yml

```
version: "2.4"

services:
  web:
    environment:
      OCTOPRINT_TUNNEL_PORT_RANGE: "15853-15858"
    ports:
      - "15853:3334"
      - "15854:3334"
      - "15855:3334"
      - "15856:3334"
      - "15857:3334"
      - "15858:3334"
```

nginx site configuration

```
server {

        server_name obico.ulbricht.cloud;
        client_max_body_size 0;

        location / {
                proxy_pass http://127.0.0.1:3334/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 6000;
                proxy_connect_timeout 6000;
                proxy_send_timeout 6000;
                client_max_body_size 0;
        }


    listen 443 ssl; # managed by Certbot
#    listen 15853 ssl;
#    listen 15854 ssl;
#    listen 15855 ssl;
#    listen 15856 ssl;
#    listen 15857 ssl;
#    listen 15858 ssl;

    ssl_certificate /etc/letsencrypt/live/obico.ulbricht.cloud/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/obico.ulbricht.cloud/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

     location /ws/ {
                proxy_pass http://127.0.0.1:3334/ws/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
}

server {
    if ($host = obico.ulbricht.cloud) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



        server_name obico.ulbricht.cloud;
    listen 80;
    return 404; # managed by Certbot


}
```

The nginx error.log has nothing interesting in it. The problem is, that the connection simply times out.

Greetings
DerKnerd
